// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/digest": {
            "post": {
                "description": "Generate digest for testing apis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Generate digest",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "req_body",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/wallet/balance": {
            "post": {
                "description": "Get the current balance of a wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Get wallet balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-UserId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Digest",
                        "name": "X-Digest",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Wallet ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "/v1/wallet/check": {
            "post": {
                "description": "Check if a wallet exists for the given wallet ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Check if a wallet exists",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-UserId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Digest",
                        "name": "X-Digest",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Wallet ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/v1/wallet/topup": {
            "post": {
                "description": "Top up a wallet with the given amount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Top up a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-UserId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Digest",
                        "name": "X-Digest",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Top up request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TopUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/wallet/transactions": {
            "post": {
                "description": "Get the total number and amount of transactions for the current month",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Get transactions for the current month",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-UserId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Digest",
                        "name": "X-Digest",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Wallet ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.RequestModel": {
            "type": "object",
            "required": [
                "wallet_id"
            ],
            "properties": {
                "wallet_id": {
                    "type": "string"
                }
            }
        },
        "models.TopUpRequest": {
            "type": "object",
            "required": [
                "amount",
                "wallet_id"
            ],
            "properties": {
                "amount": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
